apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storageclass
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp2
allowedTopologies:
- matchLabelExpressions:
    - key: topology.ebs.csi.aws.com/zone
      values:
      - us-west-2