apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: alpha
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-storageclass
  resources:
    requests:
      storage: 4Gi